{
    "devices":[
        {
          "name": "lighthouse_b",
          "type": "Tracking Reference",
          "serial":"LHB-C2B156E3"
        },
        {
          "name": "right_controller",
          "type": "Controller",
          "serial":"LHR-62A03077"
        }
    ]
}
